name: Bug Report
description: Signaler un bug détecté lors d'un test
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: input
    id: related_test
    attributes:
      label: Test Case associé
      placeholder: Ex. #12
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      placeholder: Décrire clairement le problème
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Étapes pour reproduire le bug
      placeholder: |
        1. Se connecter
        2. Cliquer sur "Profil"
        3. Erreur affichée
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Comportement attendu
      placeholder: Le profil doit s’afficher correctement
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Sévérité
      options:
        - Critique
        - Majeure
        - Mineure
    validations:
      required: true
